version: '3.8'

volumes:
  postgres-data:
  rabbitmq-data:

networks:
  internal:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VARIANT:  bullseye
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    env_file:
        - .env
    networks:
      - internal

    volumes:
      - ..:/workspace:cached

    # Override default command so things don't shut down after the process ends.
    command: "bash -c 'sleep infinity'"

    # user: vscode

  postgres:
    image: postgres:14.1
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - internal
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  rabbitmq:
    image: rabbitmq:3-management-alpine
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
    networks:
      - internal
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 3
